SkyblockSettings:
  #Default settings for each island.
  IslandSettings:
    - MaxLevel: 3
      Levels:
        #Chances are relative, i.e DIAMOND_ORE Has a chance of 5/(5+5+10+10+15+20+100)%  which is 1/33 chance of spawning.
        1:
          - DIAMOND_ORE: 5
          - EMERALD_ORE: 5
          - LAPIS_ORE: 10
          - REDSTONE_ORE: 10
          - GOLD_ORE: 10
          - IRON_ORE: 15
          - COAL_ORE: 20
          - COBBLESTONE: 100
        2:
          - EMERALD_ORE: 5
          - DIAMOND_ORE: 7.5
          - REDSTONE_ORE: 15
          - IRON_ORE: 15
          - GOLD_ORE: 12.5
          - LAPIS_ORE: 10
          - SMOOTH_STONE: 25
          - COBBLESTONE: 75
        3:
          - EMERALD_ORE: 7.5
          - DIAMOND_ORE: 5.75
          - DIAMOND_BLOCK: 0.25
          - IRON_BLOCK: 0.5
          - GOLD_ORE: 12
          - GOLD_BLOCK: 0.5
          - COAL_BLOCK: 5
          - COAL_ORE: 15
          - SMOOTH_STONE: 50
          - COBBLESTONE: 50